name: flash_chat
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0<3.0.0"

dependencies:
  flutter:
    sdk: flutter
  animated_text_kit: ^4.2.1
  cupertino_icons: ^0.1.2
  firebase_core: ^1.10.6
  firebase_auth: ^3.3.4
  cloud_firestore: ^3.1.5
  modal_progress_hud_nsn: ^0.1.0-nullsafety-1
  image_picker: ^0.8.4+4
  firebase_storage: ^10.2.4
  firebase_app_check: ^0.0.6+3
  rflutter_alert: ^2.0.4
  flutter_linkify: ^5.0.2
  url_launcher: ^6.0.17


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - images/

